name: Build & deploy spring apps

on: 
  push:
    branches:
      - main

jobs: 
  build: 
    name: build & deploy spring app
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: 17

      - name: unit test
        run: mvn -B --file pom.xml test

      - name: build the application
        run: mvn -B --file pom.xml clean package -DskipTests

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-app:latest


